### ISSUE TITLE
5.16 add envelop and peripheraloperation to a path , upload failed

### ISSUE THREAD

**Issue by vincentknw** [openTCS/opentcs#143]
## Affected version
5.16.0
## Steps to reproduce
1 add peripheral operation to path0;
2 add envelop to path0;
3 upload model to kernel

### Actual behaviour
kernel failed to save model
...

### Additional information
[20240521-10:40:27-925] WARNING kernelExecutor       o.o.common.LoggingScheduledThreadPoolExecutor.afterExecute(): Unhandled exception in executed task
java.lang.IllegalStateException: Exception saving model
	at org.opentcs.kernel.persistence.XMLFileModelPersister.saveModel(XMLFileModelPersister.java:88)
	at org.opentcs.kernel.services.StandardPlantModelService.savePlantModel(StandardPlantModelService.java:144)
	at org.opentcs.kernel.services.StandardPlantModelService.createPlantModel(StandardPlantModelService.java:182)
	at org.opentcs.kernel.extensions.rmi.StandardRemotePlantModelService.lambda$createPlantModel$1(StandardRemotePlantModelService.java:174)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Exception marshalling data
	at org.opentcs.util.persistence.v004.V004PlantModelTO.toXml(V004PlantModelTO.java:171)
	at org.opentcs.util.persistence.ModelParser.writeModel(ModelParser.java:81)
	at org.opentcs.kernel.persistence.XMLFileModelPersister.saveModel(XMLFileModelPersister.java:85)
	... 9 more
Caused by: javax.xml.bind.MarshalException

**Comment by martingr** [comment]
Thanks for reporting this issue. This has been fixed with [openTCS 5.17](https://github.com/openTCS/opentcs/releases/v5.17.0) which was released just yesterday.
